from openpyxl import Workbook
from core.output.sensitivity_writer import write_sensitivity_matrix
from core.output.scenario_writer import write_scenario_analysis
from core.output.forecast_writer import (
    write_forecast_summary,
    write_model_forecast_summary,
)

def create_financial_model_workbook(
    output_path,
    company_name,
):
    """
    Create the base financial model workbook.
    """

    workbook = Workbook()

    # Remove default sheet
    default_sheet = workbook.active
    workbook.remove(default_sheet)

    # Create model sections
    workbook.create_sheet("Cover")
    workbook.create_sheet("Assumptions")
    workbook.create_sheet("Historical Financials")
    workbook.create_sheet("Income Statement")
    workbook.create_sheet("Balance Sheet")
    workbook.create_sheet("Cash Flow")
    workbook.create_sheet("Free Cash Flow")
    workbook.create_sheet("DCF Valuation")
    workbook.create_sheet("Sensitivity")
    workbook.create_sheet("Scenarios")

    # Cover
    cover = workbook["Cover"]

    cover["A1"] = company_name
    cover["A2"] = "Automated Financial Model"
    cover["A3"] = "Generated by FinModel-AI"

    workbook.save(output_path)

    return output_path
from core.data.historical_financials import HistoricalFinancials


def write_historical_financials(
    workbook,
    financials,
):
    """
    Write historical financial data into the
    Historical Financials worksheet.
    """

    sheet = workbook["Historical Financials"]

    headers = [
        "Year",
        "Revenue",
        "COGS",
        "Operating Expenses",
        "Depreciation",
        "Interest Expense",
        "Taxes",
        "Cash",
        "Total Debt",
        "Total Assets",
        "Shareholders Equity",
    ]

    for column, header in enumerate(headers, start=1):
        sheet.cell(
            row=1,
            column=column,
            value=header,
        )

    for row_number, financial in enumerate(
        financials,
        start=2,
    ):
        sheet.cell(row=row_number, column=1, value=financial.year)
        sheet.cell(row=row_number, column=2, value=financial.revenue)
        sheet.cell(row=row_number, column=3, value=financial.cogs)
        sheet.cell(
            row=row_number,
            column=4,
            value=financial.operating_expenses,
        )
        sheet.cell(
            row=row_number,
            column=5,
            value=financial.depreciation,
        )
        sheet.cell(
            row=row_number,
            column=6,
            value=financial.interest_expense,
        )
        sheet.cell(row=row_number, column=7, value=financial.taxes)
        sheet.cell(row=row_number, column=8, value=financial.cash)
        sheet.cell(row=row_number, column=9, value=financial.total_debt)
        sheet.cell(
            row=row_number,
            column=10,
            value=financial.total_assets,
        )
        sheet.cell(
            row=row_number,
            column=11,
            value=financial.shareholders_equity,
        )

    return sheet
def write_assumptions(
    workbook,
    assumptions,
    discount_rate,
    terminal_growth_rate,
):
    """
    Write financial modeling assumptions
    into the Assumptions worksheet.
    """

    sheet = workbook["Assumptions"]

    sheet["A1"] = "Assumption"
    sheet["B1"] = "Value"

    sheet["A2"] = "Revenue Growth"
    sheet["B2"] = assumptions.revenue_growth

    sheet["A3"] = "COGS Margin"
    sheet["B3"] = assumptions.cogs_margin

    sheet["A4"] = "Operating Expense Margin"
    sheet["B4"] = assumptions.operating_expense_margin

    sheet["A5"] = "Depreciation Margin"
    sheet["B5"] = assumptions.depreciation_margin

    sheet["A6"] = "Interest Expense"
    sheet["B6"] = assumptions.interest_expense

    sheet["A7"] = "Tax Rate"
    sheet["B7"] = assumptions.tax_rate

    sheet["A8"] = "Discount Rate / WACC"
    sheet["B8"] = discount_rate

    sheet["A9"] = "Terminal Growth Rate"
    sheet["B9"] = terminal_growth_rate

    return sheet
def write_income_statement(
    workbook,
    financials,
):
    """
    Write historical income statement data
    into the Income Statement worksheet.
    """

    sheet = workbook["Income Statement"]

    sheet["A1"] = "Income Statement"

    headers = ["Metric"]

    for financial in financials:
        headers.append(financial.year)

    for column, header in enumerate(headers, start=1):
        sheet.cell(
            row=2,
            column=column,
            value=header,
        )

    metrics = [
        "Revenue",
        "COGS",
        "Gross Profit",
        "Operating Expenses",
        "EBITDA",
        "Depreciation",
        "EBIT",
        "Interest Expense",
        "EBT",
        "Taxes",
        "Net Income",
    ]

    for row, metric in enumerate(metrics, start=3):
        sheet.cell(
            row=row,
            column=1,
            value=metric,
        )

    for column, financial in enumerate(
        financials,
        start=2,
    ):
        revenue = financial.revenue
        cogs = financial.cogs
        operating_expenses = financial.operating_expenses
        depreciation = financial.depreciation
        interest_expense = financial.interest_expense
        taxes = financial.taxes

        gross_profit = revenue - cogs

        ebitda = (
            gross_profit
            - operating_expenses
        )

        ebit = ebitda - depreciation

        ebt = ebit - interest_expense

        net_income = ebt - taxes

        values = [
            revenue,
            cogs,
            gross_profit,
            operating_expenses,
            ebitda,
            depreciation,
            ebit,
            interest_expense,
            ebt,
            taxes,
            net_income,
        ]

        for row, value in enumerate(
            values,
            start=3,
        ):
            sheet.cell(
                row=row,
                column=column,
                value=round(value, 2),
            )

    return sheet
def write_balance_sheet(
    workbook,
    financials,
):
    """
    Write historical balance sheet data
    into the Balance Sheet worksheet.
    """

    sheet = workbook["Balance Sheet"]

    sheet["A1"] = "Balance Sheet"

    headers = ["Metric"]

    for financial in financials:
        headers.append(financial.year)

    for column, header in enumerate(headers, start=1):
        sheet.cell(
            row=2,
            column=column,
            value=header,
        )

    metrics = [
        "Cash",
        "Total Assets",
        "Total Debt",
        "Shareholders Equity",
    ]

    for row, metric in enumerate(metrics, start=3):
        sheet.cell(
            row=row,
            column=1,
            value=metric,
        )

    for column, financial in enumerate(
        financials,
        start=2,
    ):
        values = [
            financial.cash,
            financial.total_assets,
            financial.total_debt,
            financial.shareholders_equity,
        ]

        for row, value in enumerate(
            values,
            start=3,
        ):
            sheet.cell(
                row=row,
                column=column,
                value=round(value, 2),
            )

    return sheet
def write_cash_flow(
    workbook,
    financials,
):
    """
    Write a simplified historical cash flow statement
    into the Cash Flow worksheet.
    """

    sheet = workbook["Cash Flow"]

    sheet["A1"] = "Cash Flow Statement"

    headers = ["Metric"]

    for financial in financials:
        headers.append(financial.year)

    for column, header in enumerate(headers, start=1):
        sheet.cell(
            row=2,
            column=column,
            value=header,
        )

    metrics = [
        "Net Income",
        "Depreciation",
        "Capital Expenditure",
        "Free Cash Flow",
    ]

    for row, metric in enumerate(metrics, start=3):
        sheet.cell(
            row=row,
            column=1,
            value=metric,
        )

    for column, financial in enumerate(
        financials,
        start=2,
    ):
        gross_profit = (
            financial.revenue
            - financial.cogs
        )

        ebitda = (
            gross_profit
            - financial.operating_expenses
        )

        ebit = ebitda - financial.depreciation

        ebt = (
            ebit
            - financial.interest_expense
        )

        net_income = ebt - financial.taxes

        # Historical model does not yet contain
        # a dedicated CapEx field, so use depreciation
        # as a temporary placeholder.
        capex = financial.depreciation

        free_cash_flow = (
            net_income
            + financial.depreciation
            - capex
        )

        values = [
            net_income,
            financial.depreciation,
            capex,
            free_cash_flow,
        ]

        for row, value in enumerate(
            values,
            start=3,
        ):
            sheet.cell(
                row=row,
                column=column,
                value=round(value, 2),
            )

    return sheet
def write_free_cash_flow(
    workbook,
    free_cash_flows,
    forecast_years,
):
    """
    Write forecast free cash flows into the
    Free Cash Flow worksheet.
    """

    sheet = workbook["Free Cash Flow"]

    sheet["A1"] = "Free Cash Flow"

    sheet["A2"] = "Metric"

    for column, year in enumerate(
        forecast_years,
        start=2,
    ):
        sheet.cell(
            row=2,
            column=column,
            value=year,
        )

    sheet["A3"] = "Free Cash Flow"

    for column, free_cash_flow in enumerate(
        free_cash_flows,
        start=2,
    ):
        sheet.cell(
            row=3,
            column=column,
            value=round(free_cash_flow, 2),
        )

    return sheet
def write_dcf_valuation(
    workbook,
    valuation,
):
    """
    Write DCF valuation results into the
    DCF Valuation worksheet.
    """

    sheet = workbook["DCF Valuation"]

    sheet["A1"] = "DCF Valuation"

    sheet["A3"] = "Enterprise Value"
    sheet["B3"] = valuation.enterprise_value

    sheet["A4"] = "Terminal Value"
    sheet["B4"] = valuation.terminal_value

    sheet["A5"] = "PV of Terminal Value"
    sheet["B5"] = valuation.terminal_present_value

    sheet["A6"] = "PV of Forecast FCF"

    pv_forecast_fcf = sum(
        valuation.present_values
    )

    sheet["B6"] = pv_forecast_fcf

    sheet["A8"] = "Total Debt"
    sheet["B8"] = valuation.total_debt

    sheet["A9"] = "Cash"
    sheet["B9"] = valuation.cash

    sheet["A10"] = "Equity Value"
    sheet["B10"] = valuation.equity_value

    sheet["A11"] = "Shares Outstanding"
    sheet["B11"] = valuation.shares_outstanding

    sheet["A12"] = "Implied Share Price"
    sheet["B12"] = valuation.implied_share_price

    return sheet
from openpyxl import Workbook

def create_financial_model_workbook(
    output_path,
    company_name,
):
    """
    Create and save the standard financial model workbook.
    """

    from openpyxl import Workbook

    workbook = Workbook()

    # Cover sheet
    cover = workbook.active
    cover.title = "Cover"

    cover["A1"] = company_name
    cover["A2"] = "Automated Financial Model"

    # Required model sheets
    sheet_names = [
        "Assumptions",
        "Historical Financials",
        "Income Statement",
        "Balance Sheet",
        "Cash Flow",
        "Free Cash Flow",
        "DCF Valuation",
        "Sensitivity",
        "Scenarios",
    ]

    for sheet_name in sheet_names:
        workbook.create_sheet(sheet_name)

    # Save workbook
    workbook.save(output_path)

    return output_path
def populate_analysis_sheets(
    workbook,
    sensitivity_matrix,
    scenarios,
):
    """
    Populate the Sensitivity and Scenarios
    worksheets using the existing analysis writers.
    """

    write_sensitivity_matrix(
        workbook=workbook,
        matrix=sensitivity_matrix,
    )

    write_scenario_analysis(
        workbook=workbook,
        scenarios=scenarios,
    )

    return workbook
def populate_forecast_summary(
    workbook,
    results,
):
    write_forecast_summary(
        workbook=workbook,
        results=results,
    )

    return workbook


def populate_model_forecast_summary(
    workbook,
    results,
):
    """
    Write actual financial model results
    into the Forecast Summary worksheet.
    """

    write_model_forecast_summary(
        workbook=workbook,
        results=results,
    )

    return workbook
    """
    Add multi-year forecast results to the workbook.
    """

    write_forecast_summary(
        workbook=workbook,
        results=results,
    )

    return workbook